charmbracelet/charm

- cmd/charm/import_keys_cmd.go
* Create data directory if it doesn't exist
* Don't always require a TUI if not forcing import
* Don't create extra subdirectory when importing keys with the TUI
> Key import improvements

- .github/workflows/go.yml
This will allow things like #18 and we could also replace `pkg/erros` with plain `fmt.Errorf`. 
We only release on Go 1.15 anyway, so this seems fair to me 🤔
> Build on Go 1.15+ only

- client/crypt.go
- go.mod
- go.sum
The client was encoding the current local time into the encryption keys and pushing them to the server. This was causing an issue when the time zones weren't matched. This fix lets the server set the `created_at` date for encryption keys.
Fixes #29.
> Fix issues with mismatched time zones on encryption keys

- kv/kv.go
By default, Badger sets the .vlog files size to 2GB. This change will shrink them to 20MB. It puts a limit of 10MB on the value size, but leaves open the option for custom sizing via Badger options.
> Decrease default BadgerDB vlog value size to 10MB

- .goreleaser.yml
This tiny update updates the image used in the footer added to releases by `goreleaser`.
> Update image in release footer

- server/storage/local/storage.go
- server/storage/local/storage_test.go
> Return an error if we try to write a file to /

- cmd/fs.go
The `fs copy` command will use the same path if the source file is a
regular file and no destination path was specified. For example:
`charm fs cp foo charm:` will copy file foo to `charm:/foo`
which is convenient when you don't want to specify a different file name
for the destination file, saving you some typing.
Currently a proposal, happy to add some tests if accepted.
> Use the same path if no destination path specified

- main.go
Cobra already prints the errors to stderr when using `RunE` to execute
the commands, so adding an extra `fmt.Println` here duplicates errors.
Without the patch:
With the patch:
> Don't print CLI errors twice

- client/crypt.go
`cryptCheck` can return a number of different errors so it's useful to
wrap the error returned.
> Wrap cryptCheck errors

- cmd/serve.go
- server/http.go
- server/server.go
Fixes health port type also, now being consistent with SSH and HTTP port
types.
> serve: add --health-port flag

- server/server.go
Check for nils before setting DB, FS, and Stats otherwise init() will
overwrite DB, FS, and Stats if set.
Fixes: f1f42fd2391e ("Fix database initialization order")
> fix: allow using custom DB, FS and Stats

- kv/kv.go
it is not necessary to use `Sprintf` together with `filepath.Join`
> clear string formatting in database opening (path)

- fs/fs.go
fix `charm fs rm` when the path has the `charm:` prefix
> fix: fs rm with charm: prefix

- cmd/serve.go
- go.mod
- go.sum
- server/auth.go
- server/http.go
- server/middleware.go
- server/server.go
- server/ssh.go
* HTTP scheme is now determined by whether or not a tls config or files are provided.
* Implement server graceful shutdown, credit to @caarlos0 
* Recover from SSH panics
* Log server errors to an error logger
> Graceful shutdown, recover from SSH panics, and use error logger

- .github/workflows/build.yml
Go 1.16 is the minimum requirement for our workflows.
> Require Go 1.16

- client/client.go
- client/crypt.go
- client/link.go
- cmd/cmd.go
- cmd/migrate_account.go
- cmd/post_news.go
- crypt/crypt.go
- fs/fs.go
- kv/client.go
- kv/kv.go
- main.go
- ui/keygen/keygen.go
* Move from RSA to Ed25519 for default SSH keys for Charm accounts
* Added `charm migrate-account` command to upgarade legacy accounts
* Allow for configurable key type though env vars and Config
* Move from using a default encryption key to trying all encryption keys
> Use Ed25519 keys for Charm client

- ui/keygen/keygen.go
ui/keygen ignores the passed host
Fixes: https://github.com/charmbracelet/charm/issues/93
> fix: ui/keygen not generating keys for host

- README.md
- client/http.go
- fs/fs.go
- proto/errors.go
- server/http.go
- server/middleware.go
- server/server.go
- server/ssh.go
- server/storage/local/storage.go
- server/storage/storage.go
* Use bufferless FS write requests (the encryption part still uses buffers to encrypt files but the request does not)
* Support setting server user max storage capacity via `CHARM_SERVER_USER_MAX_STORAGE`, zero is the default which means storage cap is disabled
* Read `data/.ssh/authorized_keys` if it exists to limit user access to the server
> Speed up client FS, support server user max storage capacity, use authorized_keys, and some fixes

- cmd/backup_keys.go
- cmd/import_keys.go
> fix: fix help msg

- cmd/fs.go
When `charm fs` is run without arguments, let cobra display help rather than
exiting silently.
This is accomplished by removing the `RunE` property in the `Command` struct so
that cobra can display help correctly.
> Show help for `charm fs`

- client/crypt.go
- kv/client.go
- kv/kv.go
- server/db/sqlite/storage.go
- server/link.go
Just making go-staticcheck happy, fixed capitalized error strings: https://staticcheck.io/docs/checks#ST1005
> Fixed: error strings should not be capitalized

- client/client.go
Here, `u` getting checked against a nil: 
https://github.com/charmbracelet/charm/blob/b7d991650ccde9b7d0e466c2aa2966b724217e23/client/client.go#L259
But `u` will be never nil, because here, it gets initalized as a pointer to a default initialized `charm.User` struct:
https://github.com/charmbracelet/charm/blob/b7d991650ccde9b7d0e466c2aa2966b724217e23/client/client.go#L250
I fixed it by comparing `u` value against an empty `charm.User` struct:
```go
if (*u == charm.User{}) {
return nil, errors.New("no user data received")
}
```
> Fixed: checking nil against a never-nil value

- server/server.go
- testserver/testserver.go
its always enabling the metrics, disrespecting the config.
refs #137
> fix: respect enable metrics

- server/server.go
- server/stats/noop/noop.go
- testserver/testserver.go
otherwise `cfg.Stats` will be nil and metered endpoints will fail - including tests
> fix: use a noop stats implementation if stats are disabled

- client/client.go
- cmd/backup_keys.go
- fs/README.md
- kv/kv.go
- server/http.go
- server/storage/local/storage_test.go
Replaced use of deprecated ioutil functions with their correct ones.
More info why ioutil got deprecated: https://go.dev/doc/go1.16
> Replaced deprecated ioutil package

- cmd/backup_keys.go
- cmd/backup_keys_test.go
- cmd/import_keys.go
- cmd/import_keys_test.go
- docs/backup-account.md
- docs/restore-account.md
- adds a `-o` flag to `backup-keys`, so users can backup to any filepath 
- `-o -` prints only the private key to stdout, so it can be pipes to other things, e.g. melt
- allow to restore keys from stdin
closes #128 
closes https://github.com/charmbracelet/charm/issues/116
closes https://github.com/charmbracelet/melt/pull/17
refs https://github.com/charmbracelet/melt/pull/18
> feat: backup to stdout and other paths and import from stdin

- server/http.go
- server/middleware.go
Fixed the issue with context values - `staticcheck: SA1029 - Inappropriate key in call to context.WithValue` in `middleware.go`.
And in the second file `http.go` added proper way to assert the type of a context value.
> fixed: proper way to handle context values

- client/client.go
- ui/charmclient/client.go
Fail early to avoid breaking things (namely anything involving signing) later.
> fix: fail early on invalid key types

- cmd/where.go
- main.go
> feat: output data dir with charm where

- kv/kv.go
Fixes duplicate keys referenced in #157
> fix: duplicate keys in charm/kv .Keys() function #157

- server/ssh.go
Don't report `ErrServerClosed` error when ssh server shuts down.
> fix(server): ssh server closed err

- README.md
closes #209 
I think this should be mentioned in the [Skate](https://github.com/charmbracelet/skate) docs that you can customize the skate client with these env variables and link back to this section of the Charm docs. Also, not sure how we feel about moving the install instructions, but it felt strange having it so deep into the weeds of Charm cloud.
> docs: add client env vars to README

- ui/ui.go
- ui/username/username.go
If a username is set, charm now pre-populates the input field with it in the "set username" section. Resolves #16.
I tried to incorporate some of the feedback given in https://github.com/charmbracelet/charm/pull/17#issuecomment-751406322 but I'm new to bubble tea.
> Pre-populate username

- go.mod
- go.sum
- server/http.go
- server/jwk.go
- server/middleware.go
closes https://github.com/charmbracelet/charm/issues/281
> fix: jwks validation using the wrong type 
