charmbracelet/charm

- .github/workflows/go.yml
- .gitignore
- .goreleaser.yml
- keygen/keygen_test.go
Adds builds for Windows, FreeBSD, OpenBSD & Alpine.
Disables upx.
> Update GitHub workflow and GoReleaser config

- cmd/charm/backup_keys_cmd.go
- cmd/charm/bio_cmd.go
- cmd/charm/decrypt_cmd.go
- cmd/charm/encrypt_cmd.go
- cmd/charm/id_cmd.go
- cmd/charm/jwt_cmd.go
- cmd/charm/keygen_cmd.go
- cmd/charm/keys_cmd.go
- cmd/charm/keysync_cmd.go
- cmd/charm/main.go
- cmd/charm/name_cmd.go
- ui/keygen/keygen.go
* Generate keys in relevant sub-commands when necessary
* Validate files/directory before creating backup
* Don't overwrite an existing backup file
> Key generation and backup improvements

- keygen/keygen.go
Just because the editor was complaining :)
> Fix small typo

- keygen/keygen_test.go
> Simplify test by using t.TempDir

- server/server.go
Delay database, filestore and stats initialization until the config
values have been set via command line args.
Fixes #35
> Fix database initialization order

- cmd/backup_keys.go
> fix: backup-keys should only have keys

- cmd/fs.go
- fs/fs.go
> feat: make fs cmds accept charm: URIs as args

- cmd/fs.go
add `charm fs mv`, which copies src to dst and then deletes src.
> feat: charm fs mv

- cmd/kv.go
* Added `-b` flag to `charm kv list` and `charm kv get` to optionally print binary values
* Detect if output is a TTY and print binary if it's not
* Don't print newlines after values unless a TTY is attached
Fixes #69 and #70
> Improve printing from KV

- client/client.go
- go.mod
- go.sum
- server/http.go
- server/server.go
- server/ssh.go
* Set back `CHARM_SERVER_HOST` default value
* Switch to caarlos0/env
* Introduce `CHARM_SERVER_BIND_ADDRESS` environment variable
Fixes: https://github.com/charmbracelet/charm/issues/78
> Listen on CHARM_SERVER_BIND_ADDRESS and set CHARM_SERVER_HOST default value

- go.mod
- go.sum
Switch to first public release of toktok.
> Bump toktok to v0.1.0

- proto/link.go
- server/link.go
- server/server.go
- server/ssh.go
LinkQueue handles sending/receiving link requests. It abstracts how link requests should be sent and received during the linking process.
This adds a `WithLinkQueue()` to `Config`
> feat: implement LinkQueue interface

- proto/errors.go
- server/db/db.go
- server/db/sqlite/sql.go
- server/db/sqlite/storage.go
- server/link.go
- server/server.go
- server/ssh.go
- server/stats/sqlite/sqlite.go
* Store tokens in the database
* Use toktok to generate humane-friendly tokens
* Cancel db transactions after 5 seconds timeout
> feat: store tokens in the database instead of memory

- cmd/serve.go
- cmd/serve_migrate.go
- server/db/sqlite/migration/0001_foreign_keys.go
- server/db/sqlite/migration/migration.go
- server/db/sqlite/sql.go
- server/db/sqlite/storage.go
* Add first db sql migration
* Create tables with foreign_key constraints and update and delete cascades
* Export default db name and connection options
> Add db migrate tool and fix cascade db deletions

- go.mod
- go.sum
- ui/ui.go
Fixes: https://github.com/charmbracelet/charm/issues/96
Related: https://github.com/charmbracelet/lipgloss/pull/72
> fix(ui): wrap output with terminal width

- cmd/serve.go
- go.mod
- go.sum
- server/server.go
- server/stats/prometheus/prometheus.go
Adds back Prometheus stats server
Use CHARM_SERVER_ENABLE_METRICS=true to enable the stats server
> feat: add prometheus stats server

- ui/common/views.go
> fix(ui): link yes/no buttons width keep increasing

- ui/info/info.go
#110 
https://user-images.githubusercontent.com/15822994/164156140-ca56cfe0-5be2-46a7-a8de-a7b3040b2ebc.mp4
> feat: show host in UI

- server/db/sqlite/storage.go
Remove an unused func and simplify the defer.
> fix: remove some unused code

- README.md
- docs/self-hosting.md
> Docs: self-hosting + storage info

- cmd/backup_keys.go
- cmd/backup_keys_test.go
- server/auth_test.go
- server/ssh.go
- testserver/testserver.go
did something a little different on the backup closing all writers thing... cc/ @bashbunni 
- improve error handling when closing tar stuff on backup keys
- improve backup tests to check for number of files as well
- use testserver on backup tests
- moved test server stuff to another package so it can be reused
> fix: backup keys

- .gitignore
- cmd/backup_keys.go
- cmd/backup_keys_test.go
- server/auth_test.go
- server/ssh.go
- testserver/testserver.go
#91 
I can squash these into a single commit if you'd prefer
> test: Add backup tests

- README.md
- crypt/README.md
> docs: update encryption example

- README.md
We will need to update these docs once we add `melt` support for backups, but I do think it's a necessary addition in the meantime.
> docs: how to backup accounts

- README.md
refs https://github.com/charmbracelet/skate/pull/39
> docs: charm fs faq

- kv/README.md
> docs: how to delete database charm kv

- proto/link.go
- server/link.go
- server/server.go
- server/ssh.go
> feat(server): support custom link timeout duration

- docs/backup-account.md
- docs/restore-account.md
- docs/self-hosting.md
https://github.com/charmbracelet/charm/pull/221
> docs: reverse proxy setup

- crypt/crypt.go
EncrytpedWriter -> EncryptedWriter
> docs: fix typo
